---
abstract: 'Provides mro functions for XS modules'
author:
  - 'Goro Fuji(gfx) <gfuji(at)cpan.org>.'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.2
  Test::More: 0.86
  XSLoader: 0.08
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XS-MRO-Compat
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  MRO::Compat: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/Perl-XS-MRO-Compat.git
version: 0.13
